branches:
  - main
  - master

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - ["@semantic-release/changelog", { changelogFile: "CHANGELOG.md" }]
  - ["@semantic-release/changelog", { changelogFile: "charts/bitwarden-password-manager-eso/CHANGELOG.md" }]
  - ["semantic-release-helm", { chartPath: "charts/bitwarden-password-manager-eso", onlyUpdateVersion: true }]
  - - "@semantic-release/git"
    - assets:
        - "charts/bitwarden-password-manager-eso/Chart.yaml"
        - "charts/bitwarden-password-manager-eso/CHANGELOG.md"
        - "charts/bitwarden-password-manager-eso/README.md"
        - "CHANGELOG.md"
        - "README.md"
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - "@semantic-release/github"