branches:
  - main
  - master

tagFormat: v${version}

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"

  # Update Chart.yaml and chart CHANGELOG
  - ["semantic-release-helm", {
      chartPath: "charts/bitwarden-password-manager-eso",
      onlyUpdateVersion: true,
      populateChangelog: true
    }]

  # Update Artifact Hub changelog annotation in Chart.yaml
  - ["@semantic-release/exec", {
      prepareCmd: "scripts/update-artifacthub-changes.sh charts/bitwarden-password-manager-eso/Chart.yaml ${nextRelease.version}"
    }]

  # Update root CHANGELOG.md
  - ["@semantic-release/changelog", { changelogFile: "CHANGELOG.md" }]

  # Regenerate README using helm-docs
  - ["@semantic-release/exec", {
      prepareCmd: "helm-docs --chart-search-root=charts/ --output-file=README.md"
    }]

  # Commit all generated files
  - ["@semantic-release/git", {
      assets: [
        "charts/bitwarden-password-manager-eso/Chart.yaml",
        "charts/bitwarden-password-manager-eso/CHANGELOG.md",
        "charts/bitwarden-password-manager-eso/README.md",
        "charts/bitwarden-password-manager-eso/artifacthub.io/changes.yaml",
        "CHANGELOG.md",
        "README.md"
      ],
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }]

  - "@semantic-release/github"