branches:
  - main
  - master

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    changelogFile: "CHANGELOG.md"
  - - "semantic-release-helm"
    chartPath: "."
    onlyUpdateVersion: true
  - - "@semantic-release/git"
    assets:
      - "Chart.yaml"
      - "CHANGELOG.md"
    message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - "@semantic-release/github"
