{{- range .Values.clusterSecretStores }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .name }}
  labels:
    {{- include "bitwarden-eso.labels" $ | nindent 4 }}
spec:
  provider:
    webhook:
      url: {{ printf "http://%s.%s.svc.cluster.local:8087/object/item/{{ .remoteRef.key }}" (include "bitwarden-eso.fullname" $) $.Release.Namespace }}
      result:
        jsonPath: {{ .jsonPath | quote }}
      headers:
        Content-Type: application/json
{{- end }}